School_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views 
from xauth import views as xauth_views
from django.views.i18n import JavaScriptCatalog



MEDIA_ROOT = getattr (settings,"MEDIA_ROOT")
MEDIA_URL = getattr (settings,"MEDIA_URL")




urlpatterns = [
    path('', views.RedirectionView.as_view(),name='redirect'),
    path('home/', views.IndexTemplateView.as_view(),name='index-view'),
    path('admin/', admin.site.urls),
    path('login/', xauth_views.CustomLoginView.as_view(), name='user-login'),
    path('logout/', xauth_views.CustomLogoutView.as_view(), name='logout'),
    path('auth/', include('xauth.urls')),
    path('parameter/', include('parameter.urls')),   
    path('management/', include('fiche_management.urls')), 
    path("signup/", xauth_views.User2CreateView.as_view(), name="user-signup"),
    path('retour/', views.back_button_view, name='back-button'),
    # path(
    #     "account-activation/<uuid:pk>/set-password/",
    #     xauth_views.SetPasswordView.as_view(),
    #     name="user-set-password",
    # ),
    path(
        "account-activation/<str:uidb64>/set-password/<str:token>",
        xauth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

parameter/urls.py
from django.urls import path
from .views import *
from parameter import views


app_name = 'parameter'

urlpatterns = [

    path(
        "parameters/ufr/list/",
        view=views.UfrListView.as_view(),
        name="uniteDeRecherche-list",
    ),
    path(
        "parameters/ufr/create/",
        view=views.UfrCreateView.as_view(),
        name="uniteDeRecherche-create",
    ),
    path(
        "parameters/ufr/<uuid:pk>/detail/",
        view=views.UfrDetailView.as_view(),
        name="uniteDeRecherche-detail",
    ),
    path(
        "parameters/ufr/<uuid:pk>/update/",
        view=views.UfrUpdateView.as_view(),
        name="uniteDeRecherche-update",
    ),
    path(
        "parameters/ufr/<uuid:pk>/delete/",
        view=views.UfrDeleteView.as_view(),
        name="uniteDeRecherche-delete",
    ),


    ##Departements urls

    path(
        "parameters/departement/list/",
        view=views.DepartementListView.as_view(),
        name="departement-list",
    ),
    path(
        "parameters/departement/create/",
        view=views.DepartementCreateView.as_view(),
        name="departement-create",
    ),
    path(
        "parameters/departement/<uuid:pk>/detail/",
        view=views.DepartementDetailView.as_view(),
        name="departement-detail",
    ),
    path(
        "parameters/departement/<uuid:pk>/update/",
        view=views.DepartementUpdateView.as_view(),
        name="departement-update",
    ),
    path(
        "parameters/departement/<uuid:pk>/delete/",
        view=views.DepartementDeleteView.as_view(),
        name="departement-delete",
    ),


    ##filieres urls

    path(
        "parameters/filiere/list/",
        view=views.FiliereListView.as_view(),
        name="filiere-list",
    ),
    path(
        "parameters/filiere/create/",
        view=views.FiliereCreateView.as_view(),
        name="filiere-create",
    ),
    path(
        "parameters/filiere/<uuid:pk>/detail/",
        view=views.FiliereDetailView.as_view(),
        name="filiere-detail",
    ),
    path(
        "parameters/filiere/<uuid:pk>/update/",
        view=views.FiliereUpdateView.as_view(),
        name="filiere-update",
    ),
    path(
        "parameters/filiere/<uuid:pk>/delete/",
        view=views.FiliereDeleteView.as_view(),
        name="filiere-delete",
    ),
    
     ##niveau urls

     path(
         "parameters/niveau/list/",
         view=views.NiveauListView.as_view(),
         name="niveau-list",
     ),
     path(
         "parameters/niveau/create/",
         view=views.NiveauCreateView.as_view(),
         name="niveau-create",
     ),
    path(
        "parameters/niveau/<uuid:pk>/detail/",
         view=views.NiveauDetailView.as_view(),
         name="niveau-detail",
     ),
     path(
         "parameters/niveau/<uuid:pk>/update/",
         view=views.NiveauUpdateView.as_view(),
         name="niveau-update",
     ),
     path(
        "parameters/niveau/<uuid:pk>/delete/",
         view=views.NiveauDeleteView.as_view(),
         name="niveau-delete",
     ),
    
    
    ##semestre urls

    path(
        "parameters/semestre/list/",
        view=views.SemestreListView.as_view(),
        name="semestre-list",
    ),
    path(
        "parameters/semestre/create/",
        view=views.SemestreCreateView.as_view(),
        name="semestre-create",
    ),
    path(
        "parameters/semestre/<uuid:pk>/detail/",
        view=views.SemestreDetailView.as_view(),
        name="semestre-detail",
    ),
    path(
        "parameters/semestre/<uuid:pk>/update/",
        view=views.SemestreUpdateView.as_view(),
        name="semestre-update",
    ),
    path(
        "parameters/semestre/<uuid:pk>/delete/",
        view=views.SemestreDeleteView.as_view(),
        name="semestre-delete",
    ),
    
        ##UE urls

    path(
        "parameters/ue/list/",
        view=views.UeListView.as_view(),
        name="ue-list",
    ),
    path(
        "parameters/ue/create/",
        view=views.UeCreateView.as_view(),
        name="ue-create",
    ),
    path(
        "parameters/ue/<uuid:pk>/detail/",
        view=views.UeDetailView.as_view(),
        name="ue-detail",
    ),
    path(
        "parameters/ue/<uuid:pk>/update/",
        view=views.UeUpdateView.as_view(),
        name="ue-update",
    ),
    path(
        "parameters/ue/<uuid:pk>/delete/",
        view=views.UeDeleteView.as_view(),
        name="ue-delete",
    ),
    
    
    ##module urls

    path(
        "parameters/modules/list/",
        view=views.ModuleListView.as_view(),
        name="module-list",
    ),
    path(
        "parameters/modules/create/",
        view=views.ModuleCreateView.as_view(),
        name="module-create",
    ),
    path(
        "parameters/modules/<uuid:pk>/detail/",
        view=views.ModuleDetailView.as_view(),
        name="module-detail",
    ),
    path(
        "parameters/modules/<uuid:pk>/update/",
        view=views.ModuleUpdateView.as_view(),
        name="module-update",
    ),
    path(
        "parameters/modules/<uuid:pk>/delete/",
        view=views.ModuleDeleteView.as_view(),
        name="module-delete",
    ),

# Promotion

    path(
        "parameters/promotion/list/",
        view=views.PromotionListView.as_view(),
        name="promotion-list",
    ),
    path(
        "parameters/promotion/create/",
        view=views.PromotionCreateView.as_view(),
        name="promotion-create",
    ),
    path(
    "parameters/promotion/<uuid:pk>/detail/",
    view=views.PromotionDetailView.as_view(),
    name="promotion-detail",
        ),

    path(
        "parameters/promotion/<uuid:pk>/update/",
        view=views.PromotionUpdateView.as_view(),
        name="promotion-update",
    ),
    path(
        "parameters/promotion/<uuid:pk>/delete/",
        view=views.PromotionDeleteView.as_view(),
        name="promotion-delete",
    ),

    # Année Universitaire

    path(
        "parameters/annee_univ/list/",
        view=views.Annee_univListView.as_view(),
        name="annee_univ-list",
        ),
    path(
        "parameters/annee_univ/create/",
        view=views.Annee_univCreateView.as_view(),
        name="annee_univ-create",
    ),
    path(
        "parameters/annee_univ/<uuid:pk>/detail/",
        view=views.Annee_univDetailView.as_view(),
        name="annee_univ-detail",
        ),

    path(
        "parameters/annee_univ/<uuid:pk>/update/",
        view=views.Annee_univUpdateView.as_view(),
        name="annee_univ-update",
    ),

    
    path(
        "parameters/annee_univ/<uuid:pk>/delete/",
        view=views.Annee_univDeleteView.as_view(),
        name="annee_univ-delete",
    ),


    # Volume_horaire

    path(
        "parameters/volume_horaire/list/",
        view=views.VolumeHoraireListView.as_view(),
        name="volume_horaire-list",
        ),
    path(
        "parameters/volume_horaire/create/",
        view=views.VolumeHoraireCreateView.as_view(),
        name="volume_horaire-create",
    ),
    path(
        "parameters/volume_horaire/<uuid:pk>/detail/",
        view=views.VolumeHoraireDetailView.as_view(),
        name="volume_horaire-detail",
        ),

    path(
        "parameters/volume_horaire/<uuid:pk>/update/",
        view=views.VolumeHoraireUpdateView.as_view(),
        name="volume_horaire-update",
    ),

    
    path(
        "parameters/volume_horaire/<uuid:pk>/delete/",
        view=views.VolumeHoraireDeleteView.as_view(),
        name="volume_horaire-delete",
    ),
##Grade urls

    path(
        "parameters/grade/list/",
        view=views.GradeListView.as_view(),
        name="grade-list",
    ),
    path(
        "parameters/grade/create/",
        view=views.GradeCreateView.as_view(),
        name="grade-create",
    ),
    path(
        "parameters/grade/<uuid:pk>/detail/",
        view=views.GradeDetailView.as_view(),
        name="grade-detail",
    ),
    path(
        "parameters/grade/<uuid:pk>/update/",
        view=views.GradeUpdateView.as_view(),
        name="grade-update",
    ),
    path(
        "parameters/grade/<uuid:pk>/delete/",
        view=views.GradeDeleteView.as_view(),
        name="grade-delete",
    ),
    


]

web/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from web import views
from xauth import views as auth_views

handler400 = "web.errors_views.handler_400_view"
handler403 = "web.errors_views.handler_403_view"
handler404 = "web.errors_views.handler_404_view"
handler500 = "web.errors_views.handler_500_view"

MEDIA_ROOT = getattr(settings, "MEDIA_ROOT")
MEDIA_URL = getattr(settings, "MEDIA_URL")
ONLINE = getattr(settings, "ONLINE")

urlpatterns = [
    path("", views.CustomRedirectView.as_view(), name="redirect-index"),
    # path(
    #     "sitemap.xml",
    #     sitemap,
    #     {"sitemaps": sitemaps},
    #     name="django.contrib.sitemaps.views.sitemap",
    # ),
    path("home/", views.IndexTemplateView.as_view(), name="index-view"),
    path("admin/", admin.site.urls),
    path("parameters/", include("parameter.urls")),
    path("import-export/", include("ie_app.urls")),
    path("auth/", include("xauth.urls")),
    path("login/", auth_views.CustomLoginView.as_view(), name="user-login"),
    path("signup/", auth_views.User2CreateView.as_view(), name="user-signup"),
    path("logout/", auth_views.CustomLogoutView.as_view(), name="user-logout"),
    path(
        "account-activation/<uuid:pk>/set-password/",
        auth_views.SetPasswordView.as_view(),
        name="user-set-password",
    ),
    path(
        "password-reset/request/",
        auth_views.CustomPasswordResetView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/request-done/",
        auth_views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-request-done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        auth_views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete",
    ),


] + static(MEDIA_URL, document_root=MEDIA_ROOT)

parameter/templates/departement/create_departement.html
{% extends 'base.html' %}
{% load icon %}
{% load humanize %}
{% load static %}

{% block breadcrumb %}
    <a href="{% url 'index-view' %}">Accueil</a> &gt;
    <a href="#">Liste des départements</a> 
    <a href="#">Creation de département</a> 
    {{ departement.name }}
{% endblock %}

{% block content %}


<div class="mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Ajouter un Département</h4>
                </div>
                <div class="card-body">
                    <django-formset endpoint="{{ request.path }}" csrf-token="{{ csrf_token }}">
                        {{ form }}
                    
                        <div class="offset-sm-3  my-5">
                            {% include 'button.html' with label="Enregistrer" color="btn-success" icon_name='"save"' process="spinner -> submit -> okay(2000) -> proceed !~ bummer(10000) -> scrollToError" %}
                            {% if can_rerender %}
                            {% include 'button.html' with label="Enregistrer et Continuer" color="btn-info" icon_name='"refresh-cw"' process="spinner -> submit -> okay(2000) -> proceed -> reload !~ bummer(10000)" %}
                            {% endif %}
                            <a href="{{ list_url }}">{% include 'button.html' with label="Annuler" color="btn-warning" icon_name='"x"' process="spinner -> reset -> proceed({{request.META.HTTP_REFERER}})" %}</a>
                        </div>
                    
                      </django-formset>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

parameter/templates/departement/delete-departement.html
<h1>Confirmer la suppression de {{ departements.title }}</h1>

<form method="post">
    {% csrf_token %}
    <button type="submit">Oui, supprimer</button>
    <a href="{%  url 'parameter:departement-list' %}">Annuler</a>
</form>

parameter/templates/departement/detail-departement.html
{% extends 'base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid py-4">
    <!-- Card Wrapper -->
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white text-center py-3">
            <h5 class="m-0 font-weight-bold">Informations sur le département</h5>
        </div>
        <div class="card-body px-4">
            <!-- Two-Column Layout -->
            <div class="row">
                <!-- Colonne Gauche -->
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th scope="row" style="width: 40%;">Code :</th>
                                <td>{{ object.code }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Libellé :</th>
                                <td>{{ object.label }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- Colonne Droite -->
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th scope="row" style="width: 40%;">UFR :</th>
                                <td>{{ object.ufr }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Description :</th>
                                <td>{{ object.description }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Pied de page de la carte -->
        <div class="card-footer bg-light text-right">
            <a href="{% url 'parameter:departement-update' object.pk %}" class="btn btn-outline-warning btn-sm">
                <i class="fas fa-edit"></i> Modifier
            </a>
            <!-- Bouton de suppression intégré avec le modal -->
            <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">
                <i class="fas fa-trash"></i> Supprimer
            </button>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<!-- Modal de confirmation de suppression -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="deleteConfirmationLabel">Confirmer la suppression</h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Êtes-vous sûr de vouloir supprimer cette unité d'enseignement : <strong>{{ object.label }}</strong> ?</p>
                <p class="text-muted">Cette action est irréversible.</p>
            </div>
            <div class="modal-footer">
                <form method="post" action="{% url 'parameter:departement-delete' object.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Oui, supprimer</button>
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

parameter/templates/departement/list-departement.html
{% extends "models/list.html" %}
{% load icon %}
{% load humanize %}
{% load static %}



{% block breadcrumb %}

{% endblock %}

{% block table-headers %}
<th>Code</th>
<th>UFR</th>
<th>Libellé</th>
{% endblock table-headers %}


{% block table-rows %}
<td>{{ object.code }}</td>
<td>{{ object.ufr }}</td>
<td>{{ object.label }}</td>
{% endblock table-rows %}



{% block other-options %}
{% endblock other-options %}



{% block javascript %}


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // Fonction pour la recherche dans le tableau
    document.getElementById('searchInput').addEventListener('keyup', function() {
        let searchValue = this.value.toLowerCase();
        let rows = document.querySelectorAll('tbody tr');

        rows.forEach(row => {
            let code = row.cells[1].textContent.toLowerCase();
            let ufr = row.cells[2].textContent.toLowerCase();
            let label = row.cells[3].textContent.toLowerCase();

            if (code.includes(searchValue) || ufr.includes(searchValue) || label.includes(searchValue)) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
</script>


{% endblock javascript %}